### ISSUE TITLE
Uncaught TypeError: EMOTELIST.show is not a function

### ISSUE THREAD

**Issue by jeffjaf** [calzoneman/sync#913]
## Website Problem ##

**Please confirm whether you've tried the following debugging steps:**

  - [x] Clearing cache and refreshing the page (On Firefox, press Ctrl+F5.  On Chrome, press F12, then right click the refresh button and click "Empty Cache and Hard Reload")
  - [x] Disabling all browser extensions
  - [x] Using a clean channel with no customizations
  
### Description of the Problem ###

    On any channel, go to Layout on the navigation bar and select 'Chat Only'.
    Then, click the 'Emote List' button positioned on the header. Nothing happens instead of showing the emote list.

### System Information ###

  - **Operating System (Windows / Mac / Linux / Android / iOS):** Windows 10 Pro
  - **Web Browser (Firefox / Chrome / Other):** Chrome
  - **Error Messages Displayed:** Uncaught TypeError: EMOTELIST.show is not a function
  - Screenshot of JavaScript Console:
![javascript-console](https://user-images.githubusercontent.com/42723798/125379979-e2bb6280-e367-11eb-9c7d-5e879a25d50a.PNG)

**Comment by calzoneman** [comment]
Confirmed, this regression was introduced 5 years ago in https://github.com/calzoneman/sync/commit/d59daab2ae33fd8d4771556b05d3e029f4469a10

**Comment by calzoneman** [comment]
Deployed.
